version: '3.5'

services:
  pgsql:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: passuieo
    container_name: db_pgsql
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
  frontend:
    build: ./example-frontend
    image: front
    ports:
      - 5000:5000
  backend:
    build: ./example-backend
    image: back
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db_pgsql
      - POSTGRES_PASSWORD=passuieo

volumes:
  database:
